### ISSUE TITLE
Create uptodate badge similar to coveralls, etc.

### ISSUE THREAD

**Issue by tdziurko** [4finance/uptodate-gradle-plugin#12]
To keep in mind

There is a badge on https://github.com/reviewninja/review.ninja (using this tool https://david-dm.org/) that shows if project is using up to date dependencies. It would be really cool to have something similar  for uptodate plugin :)

**Comment by szpak** [comment]
I have accidentally found [Version Eye](http://versioneye.com/). I put sample badges for micro-infra on a wiki page: https://github.com/4finance/micro-infra-spring/wiki/Dependencies-status

It doesn't work properly with version variables with build.gradle, so I generated report from pom.xml put in jCenter.
