### ISSUE TITLE
Artifact 'com.ofg:uptodate-gradle-plugin:1.5.0:uptodate-gradle-plugin.jar' not found

### ISSUE THREAD

**Issue by djKianoosh** [4finance/uptodate-gradle-plugin#35]
I'm seeing this error when trying to grab the latest plugin 1.5.0 (we're using an internal Nexus repo that mirrors Sonatype, Maven Central, etc). 

```
> Could not resolve all dependencies for configuration 'classpath'.
   > Artifact 'com.ofg:uptodate-gradle-plugin:1.5.0:uptodate-gradle-plugin.jar' not found.
```

**Comment by marcingrzejszczak** [comment]
Do you have also mirror of Jcenter?

**Comment by djKianoosh** [comment]
Unfortunately not yet. I put in a request to our Nexus administrator within our enterprise to add bintray/jcenter but I dont know how long that process will take.

**Comment by marcingrzejszczak** [comment]
That's why it's not visible in Maven Central. We're in progress of buing proper domains and then we will start publishing to Maven Central.
