### ISSUE TITLE
HTTPS connections should be used

### ISSUE THREAD

**Issue by szpak** [4finance/uptodate-gradle-plugin#43]
Repository queries should use HTTPS connection instead of HTTP.

**Comment by kamilszymanski** [comment]
Imo we should add an option to enable/disable using HTTPS, not enforce using it.

**Comment by szpak** [comment]
IMO HTTPS should be default. The same as in Gradle and Maven.

Do you see a good (non development) use case to use HTTP?

**Comment by kamilszymanski** [comment]
You should be able to use HTTP if you want to use intermediaries that are bypassed by encrypted tunnels.

+1 for making HTTPS the default

**Comment by szpak** [comment]
Maybe we should delay that change to version 2.0 (not so away) and introduce default HTTPS. In case of a real life request reported by our users we could add that switch (if someone needed using HTTP immediately he/she would able to turn back to 1.x until the feature is implemented).

I don't like the idea to complicate code because of someone, someday could need it.

WDYT?
